# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

deleteBranchAfterMerge: true
reportStatus: true

mergeMethod: squash

blockingLabels:
- hotfix

rules:
- requiredBaseBranches:
    - develop
  minApprovals:
    CONTRIBUTOR: 3
  requiredReviewers:
    - tokopedia-ios-bot
  requiredLabels:
    - qa-approve
- blockingBaseBranches:
    - develop
  minApprovals:
    CONTRIBUTOR: 2
  requiredLabels:
    - qa-approve
