# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

deleteBranchAfterMerge: true
reportStatus: true

mergeMethod: squash

blockingLabels:
- hotfix

requiredLabels:
- qa-approve

rules:
- requiredBaseBranches:
    - develop
  minApprovals:
    CONTRIBUTOR: 3
  requiredReviewers:
    - tokopedia-ios-bot
- requiredBaseBranches:
    - regex: ^feature
  minApprovals:
    CONTRIBUTOR: 2
